### ISSUE TITLE
Printer Dashboard Page

### ISSUE THREAD

**Issue by ConTejas624** [Purdue-3D-Printing-Club/3DPC-organizer#3]
Route: "/"

Homepage of the app, shows an overview of all active printers and if they are busy.

### TODO
- [ ] list view of printers populated from backend database
- [ ] printers display printer detail on click
- [x] printer status is displayed
