### ISSUE TITLE
New Submissions List Page

### ISSUE THREAD

**Issue by ConTejas624** [Purdue-3D-Printing-Club/3DPC-organizer#5]
Route: "/new-submissions"

Shows the list of new submissions that need to be printed

### TODO
- [x] Get the new submissions from the backend
- [x] Handle submission details
- [x] css and styling
